// Bundle the v1 deck and intake dilemmas into web/data.js for the static app.
//
//   npm run build-web
import fs from "node:fs";

const V1_AXES = [
  "warmth",
  "humor",
  "looks",
  "ambition",
  "emotional availability",
  "stability",
  "curiosity",
  "chemistry",
] as const;

const LABELS: Record<string, string> = {
  warmth: "warmth",
  humor: "humor",
  looks: "beauty",
  ambition: "drive",
  "emotional availability": "openness",
  stability: "steadiness",
  curiosity: "curiosity",
  chemistry: "spark",
};

const deckFixture = JSON.parse(fs.readFileSync("samples/candidates-seed42.json", "utf8"));
const dilemmaFixture = JSON.parse(fs.readFileSync("samples/dilemmas.json", "utf8"));

const deck = deckFixture.candidates.map((c: any) => ({
  id: c.spec.id,
  seed: c.spec.seed,
  traits: c.spec.traits,
  flawAxis: c.spec.flawAxis,
  connectionAxis: c.spec.connectionAxis,
  name: c.persona.name,
  age: c.persona.age,
  bio: c.persona.bio,
  dates: c.persona.dates,
}));

const BASE = 0.6;
const HI = 0.95;
const LO = 0.25;
const dilemmas = dilemmaFixture.dilemmas.map((d: any) => {
  const traitsFor = (favored: string) => {
    const t: Record<string, number> = {};
    for (const axis of V1_AXES) t[axis] = BASE;
    const other = d.axes.find((a: string) => a !== favored);
    t[favored] = HI;
    t[other] = LO;
    return t;
  };
  return {
    axes: d.axes,
    a: { axis: d.a.axis, line: d.a.line, traits: traitsFor(d.a.axis) },
    b: { axis: d.b.axis, line: d.b.line, traits: traitsFor(d.b.axis) },
  };
});

const payload = {
  axes: V1_AXES,
  labels: LABELS,
  question: dilemmaFixture.question,
  deck,
  dilemmas,
};

fs.mkdirSync("web", { recursive: true });
fs.writeFileSync(
  "web/data.js",
  "// Generated by `npm run build-web` — do not edit by hand.\n" +
    `window.SETTLING = ${JSON.stringify(payload, null, 2)};\n`
);
console.log(`web/data.js: ${deck.length} candidates, ${dilemmas.length} dilemmas`);
